// this structure specifies the ordering of pages on the sidebar and the pages they link to. 
var pages = [
{ name: 'Supervised Learning and Optimization', link: '#', type: 'Heading' },
{ name: 'Linear Regression', link: 'supervised/LinearRegression', type: 'Page' },
{ name: 'Logistic Regression', link: 'supervised/LogisticRegression', type: 'Page' },
{ name: 'Vectorization', link: 'supervised/Vectorization', type: 'Page' },
{ name: 'Debugging: Gradient Checking', link: 'supervised/DebuggingGradientChecking', type: 'Page' },
{ name: 'Softmax Regression', link: 'supervised/SoftmaxRegression', type: 'Page' },
{ name: 'Debugging: Bias and Variance', link: 'supervised/DebuggingBiasAndVariance', type: 'Page' },
{ name: 'Debugging: Optimizers and Objectives', link: 'supervised/DebuggingOptimizersAndObjectives', type: 'Page' },
{ name: 'Supervised Neural Networks', link: '#', type: 'Heading' },
{ name: 'Multi-Layer Neural Networks', link: 'supervised/MultiLayerNeuralNetworks', type: 'Page' },
{ name: 'Exercise: Supervised Neural Network', link: 'supervised/ExerciseSupervisedNeuralNetwork', type: 'Page' },
{ name: 'Supervised Convolutional Neural Network', link: '#', type: 'Heading' },
{ name: 'Feature Extraction Using Convolution', link: 'supervised/FeatureExtractionUsingConvolution', type: 'Page' },
{ name: 'Pooling', link: 'supervised/Pooling', type: 'Page' },
{ name: 'Exercise: Convolution and Pooling', link: 'supervised/ExerciseConvolutionAndPooling', type: 'Page' },
{ name: 'Optimization: Stochastic Gradient Descent', link: 'supervised/OptimizationStochasticGradientDescent', type: 'Page' },
{ name: 'Convolutional Neural Network', link: 'supervised/ConvolutionalNeuralNetwork', type: 'Page' },
{ name: 'Excercise: Convolutional Neural Network', link: 'supervised/ExerciseConvolutionalNeuralNetwork', type: 'Page' },
{ name: 'Unsupervised Learning', link: '#', type: 'Heading' },
{ name: 'Autoencoders', link: 'unsupervised/Autoencoders', type: 'Page'},
{ name: 'PCA Whitening', link: 'unsupervised/PCAWhitening', type: 'Page'},
{ name: 'Exercise: PCA Whitening', link: 'unsupervised/ExercisePCAWhitening', type: 'Page'},
{ name: 'Sparse Coding', link: 'unsupervised/SparseCoding', type: 'Page'},
{ name: 'ICA', link: 'unsupervised/ICA', type: 'Page'},
{ name: 'RICA', link: 'unsupervised/RICA', type: 'Page'},
{ name: 'Exercise: RICA', link: 'unsupervised/ExerciseRICA', type: 'Page'},
{ name: 'Self-Taught Learning', link: '#', type: 'Heading' },
{ name: 'Self-Taught Learning', link: 'selftaughtlearning/SelfTaughtLearning', type: 'Page'},
{ name: 'Exercise: Self-Taught Learning', link: 'selftaughtlearning/ExerciseSelfTaughtLearning', type: 'Page'},
];
