
// this structure specifies the ordering of pages on the sidebar and the pages they link to. 
var pages = [
{ name: 'Supervised Learning and Optimization', link: '#', type: 'Heading' },
{ name: 'Linear Regression', link: 'supervised/LinearRegression', type: 'Page' },
{ name: 'Logistic Regression', link: '#', type: 'Page' },
{ name: 'Vectorization', link: '#', type: 'Page' },
{ name: 'Debugging: Gradient Checking', link: '#', type: 'Page' },
{ name: 'Softmax Regression', link: '#', type: 'Page' },
{ name: 'Debugging: Bias and Variance', link: '#', type: 'Page' },
{ name: 'Debugging: Optimizers and Variance', link: '#', type: 'Page' },
{ name: 'Neural Networks', link: '#', type: 'Heading' },
{ name: 'Multi-Layer Neural Networks', link: '#', type: 'Page' },
{ name: 'Exercise: Supervised Neural Network', link: '#', type: 'Page' },
{ name: 'Unsupervised Learning', link: '#', type: 'Heading' },
{ name: 'Autoencoders', link: '#', type: 'Page'},
{ name: 'Exercise: Autoencoders', link: '#', type: 'Page'},
{ name: 'Self-Taught Learning and Unsupervised Learning', link: '#', type: 'Heading' },
{ name: 'Self-Taught Learning', link: '#', type: 'Page'},
{ name: 'Building Deep Networks for Classification', link: '#', type: 'Heading'},
{ name: 'From Self-Taught Learning to Deep Networks', link: '#', type: 'Page'},
{ name: 'Deep Networks: Overview', link: '#', type: 'Page'},
{ name: 'Stacked Autoencoders', link: '#', type: 'Page'},
{ name: 'Fine-tuning Stacked AEs', link: '#', type: 'Page'},
{ name: 'Exercise: Implement Deep Network for Digit Classification', link: '#', type: 'Page'},
];
