// this structure specifies the ordering of pages on the sidebar and the pages they link to. 
var pages = [
{ name: 'Supervised Learning and Optimization', link: '#', type: 'Heading' },
{ name: 'Linear Regression', link: 'supervised/LinearRegression', type: 'Page' },
{ name: 'Logistic Regression', link: 'supervised/LogisticRegression', type: 'Page' },
{ name: 'Vectorization', link: 'supervised/Vectorization', type: 'Page' },
{ name: 'Debugging: Gradient Checking', link: 'supervised/DebuggingGradientChecking', type: 'Page' },
{ name: 'Softmax Regression', link: '#', type: 'Page' },
{ name: 'Debugging: Bias and Variance', link: '#', type: 'Page' },
{ name: 'Debugging: Optimizers and Variance', link: '#', type: 'Page' },
{ name: 'Supervised Neural Networks', link: '#', type: 'Heading' },
{ name: 'Multi-Layer Neural Networks', link: '#', type: 'Page' },
{ name: 'Exercise: Supervised Neural Network', link: '#', type: 'Page' },
{ name: 'Supervised Convolutional Neural Network', link: '#', type: 'Heading' },
{ name: 'Feature Extraction Using Convolution', link: '#', type: 'Page' },
{ name: 'Pooling', link: '#', type: 'Page' },
{ name: 'Exercise: Convolution and Pooling', link: '#', type: 'Page' },
{ name: 'Optimization: Stochastic Gradient Descent', link: '#', type: 'Page' },
{ name: 'Convolutional Neural Network', link: '#', type: 'Page' },
{ name: 'Excercise: Convolutional Neural Network', link: '#', type: 'Page' },
{ name: 'Unsupervised Learning', link: '#', type: 'Heading' },
{ name: 'Autoencoders', link: '#', type: 'Page'},
{ name: 'PCA Whitening', link: '#', type: 'Page'},
{ name: 'Exercise: PCA Whitening', link: '#', type: 'Page'},
{ name: 'ICA', link: '#', type: 'Page'},
{ name: 'RICA', link: '#', type: 'Page'},
{ name: 'Exercise: RICA', link: '#', type: 'Page'},
{ name: 'Self-Taught Learning', link: '#', type: 'Heading' },
{ name: 'Self-Taught Learning', link: '#', type: 'Page'},
{ name: 'Exercise: Self-Taught Learning', link: '#', type: 'Page'},
];
